numero1=float(input(" primer numero: "))
numero2=float(input("segundo numero: "))

print("Suma")
print(f"{numero1} + {numero2} = {numero1 + numero2}")
print("Resta")
print(f"{numero1} - {numero2} = {numero1 - numero2}")
print("Multiplicación")
print(f"{numero1} * {numero2} = {numero1 * numero2}"    )
print("División")
print(f"{numero1} / {numero2} = {numero1 / numero2}")
print("Modulo")
print(f"{numero1} % {numero2} = {numero1 % numero2}")
print("Exponente")
print(f"{numero1} ** {numero2} = {numero1 ** numero2}")